baseURL = 'https://jchai01.github.io/'
languageCode = 'en-us'
title = 'Home'

theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Joseph Chai"
  # info = "Just Documenting my journey in tech."
  # description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/jchai01"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa fa-gitlab fa-2x"
#   weight = 2
#   url = "https://gitlab.com/johndoe/"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa fa-twitter fa-2x"
#   weight = 3
#   url = "https://twitter.com/johndoe/"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/joseph-chai-163b6695/"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
